name: Build and Deploy to ACI

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Azure registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Compile the project
        run: yarn install && yarn build

      - name: Build the Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.AZURE_REGISTRY }}/devops-app:${{ github.sha }}
          file: ./Dockerfile
          context: .

      - name: Deploy to ACI
        uses: azure/aci-deploy@v1
        with:
          name: devops-app
          resource-group: ${{ secrets.AZURE_REGISTRY_GROUP }}
          dns-name-label: devops-app${{ github.run_number }}
          image: ${{ secrets.AZURE_REGISTRY }}/devops-app:${{ github.sha }}
          registry-login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          location: ${{ secrets.AZURE_REGISTRY_REGION }}
          ports: 80