name: Build and Deploy to ACI

on:
  push:
    branches: [main, azure-deployment]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Azure
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Compile the project
        run: yarn install && yarn build

      - name: Build the Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/devops-app:${{ github.sha }}
          file: ./Dockerfile
          context: .

      - name: Deploy to ACI
        uses: azure/CLI@v2
        with:
          azure_rm_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          command: |
              az container group create \
                --name devops-app \
                --image aiizondevopsapp.azurecr.io/devops-app:${{ github.sha }} \
                --resource-group appsvc_linux_centralus_basic \
                --location West Europe \
                --ip-address Public \
                --ports 80