name: Cypress tests

on:
  push

jobs:
  cypress:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run preview
          config: baseUrl=http://localhost:4173
          browser: firefox